name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Copy files to EC2 instance
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_PUBLIC_IP: 52.206.138.43
        run: |
          scp -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY app.py ec2-user@$EC2_PUBLIC_IP:/home/ec2-user/app.py
          scp -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY requirements.txt ec2-user@$EC2_PUBLIC_IP:/home/ec2-user/requirements.txt
          scp -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY model.pkl ec2-user@$EC2_PUBLIC_IP:/home/ec2-user/model.pkl

      - name: SSH into EC2 instance and set up the Flask app
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_PUBLIC_IP: 52.206.138.43
        run: |
          ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY ec2-user@$EC2_PUBLIC_IP << 'EOF'
            sudo yum update -y
            sudo yum install -y python3 python3-pip
            pip3 install -r /home/ec2-user/requirements.txt
            nohup python3 /home/ec2-user/app.py &
          EOF
